name: Deploy VitePress to learn.antarikchya.org.np/e-cube
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build VitePress site
        run: npm run docs:build
          
      - name: Deploy via SFTP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}         # server_IP or domain without sftp://
          username: ${{ secrets.SFTP_USERNAME }} # cPanel username
          password: ${{ secrets.SFTP_PASSWORD }} # cPanel password
          port: 22
          source: ".vitepress/dist/"
          target: "/home/antarikc/learn.antarikchya.org.np/ecube/"
